name: CI for building LLVM
on: [push, pull_request]

jobs:
  linux-x86_64:
    name: linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: sh linux-x86_64.sh
      - uses: actions/upload-artifact@master
        with:
          name: llvm-9.0.0-linux-x86_64
          path: llvm-9.0.0-linux-x86_64.tar.gz
  darwin-x86_64:
    name: darwin-x86_64
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: sh darwin-x86_64.sh
      - uses: actions/upload-artifact@master
        with:
          name: llvm-9.0.0-darwin-x86_64
          path: llvm-9.0.0-darwin-x86_64.tar.gz
